### ISSUE TITLE
Missing moment dependency

### ISSUE THREAD

**Issue by antoniovizuete** [alpine-code/node-red-contrib-camunda#5]
Hi there!

When you try to install it, you get an error:
@alpine-code/node-red-contrib-camunda:camunda-workflow-instance : Error: Cannot find module 'moment' (line:2)

I've taken a look at package.json and the moment dependency is missing.

Thanks in advance

**Comment by ilzenzo** [comment]
Hi Antonio!

Embarrassing! 😁
I lack of some basic testing infrastructure...

Just  #fixed, enjoy!
